// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: protos/rpc-demo.proto

package __

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCDemo_GetMultCoords_FullMethodName = "/RPCDemoPkg.RPCDemo/GetMultCoords"
	RPCDemo_GetImage_FullMethodName      = "/RPCDemoPkg.RPCDemo/GetImage"
	RPCDemo_GetTrailer_FullMethodName    = "/RPCDemoPkg.RPCDemo/GetTrailer"
	RPCDemo_GetVelocity_FullMethodName   = "/RPCDemoPkg.RPCDemo/GetVelocity"
)

// RPCDemoClient is the client API for RPCDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCDemoClient interface {
	GetMultCoords(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultCoords, error)
	GetImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error)
	GetTrailer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TrailerStatus, error)
	GetVelocity(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Velocities, error)
}

type rPCDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCDemoClient(cc grpc.ClientConnInterface) RPCDemoClient {
	return &rPCDemoClient{cc}
}

func (c *rPCDemoClient) GetMultCoords(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultCoords, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultCoords)
	err := c.cc.Invoke(ctx, RPCDemo_GetMultCoords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCDemoClient) GetImage(ctx context.Context, in *ImageRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, RPCDemo_GetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCDemoClient) GetTrailer(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TrailerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrailerStatus)
	err := c.cc.Invoke(ctx, RPCDemo_GetTrailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCDemoClient) GetVelocity(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Velocities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Velocities)
	err := c.cc.Invoke(ctx, RPCDemo_GetVelocity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCDemoServer is the server API for RPCDemo service.
// All implementations must embed UnimplementedRPCDemoServer
// for forward compatibility.
type RPCDemoServer interface {
	GetMultCoords(context.Context, *empty.Empty) (*MultCoords, error)
	GetImage(context.Context, *ImageRequest) (*ImageResponse, error)
	GetTrailer(context.Context, *empty.Empty) (*TrailerStatus, error)
	GetVelocity(context.Context, *empty.Empty) (*Velocities, error)
	mustEmbedUnimplementedRPCDemoServer()
}

// UnimplementedRPCDemoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCDemoServer struct{}

func (UnimplementedRPCDemoServer) GetMultCoords(context.Context, *empty.Empty) (*MultCoords, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultCoords not implemented")
}
func (UnimplementedRPCDemoServer) GetImage(context.Context, *ImageRequest) (*ImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedRPCDemoServer) GetTrailer(context.Context, *empty.Empty) (*TrailerStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrailer not implemented")
}
func (UnimplementedRPCDemoServer) GetVelocity(context.Context, *empty.Empty) (*Velocities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVelocity not implemented")
}
func (UnimplementedRPCDemoServer) mustEmbedUnimplementedRPCDemoServer() {}
func (UnimplementedRPCDemoServer) testEmbeddedByValue()                 {}

// UnsafeRPCDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCDemoServer will
// result in compilation errors.
type UnsafeRPCDemoServer interface {
	mustEmbedUnimplementedRPCDemoServer()
}

func RegisterRPCDemoServer(s grpc.ServiceRegistrar, srv RPCDemoServer) {
	// If the following call pancis, it indicates UnimplementedRPCDemoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCDemo_ServiceDesc, srv)
}

func _RPCDemo_GetMultCoords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCDemoServer).GetMultCoords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCDemo_GetMultCoords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCDemoServer).GetMultCoords(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCDemo_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCDemoServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCDemo_GetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCDemoServer).GetImage(ctx, req.(*ImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCDemo_GetTrailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCDemoServer).GetTrailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCDemo_GetTrailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCDemoServer).GetTrailer(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCDemo_GetVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCDemoServer).GetVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCDemo_GetVelocity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCDemoServer).GetVelocity(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCDemo_ServiceDesc is the grpc.ServiceDesc for RPCDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RPCDemoPkg.RPCDemo",
	HandlerType: (*RPCDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMultCoords",
			Handler:    _RPCDemo_GetMultCoords_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _RPCDemo_GetImage_Handler,
		},
		{
			MethodName: "GetTrailer",
			Handler:    _RPCDemo_GetTrailer_Handler,
		},
		{
			MethodName: "GetVelocity",
			Handler:    _RPCDemo_GetVelocity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/rpc-demo.proto",
}
