# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import rpc_demo_pb2 as rpc__demo__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rpc_demo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RPCDemoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMultCoords = channel.unary_unary(
                '/RPCDemoPkg.RPCDemo/GetMultCoords',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=rpc__demo__pb2.MultCoords.FromString,
                _registered_method=True)
        self.GetImage = channel.unary_unary(
                '/RPCDemoPkg.RPCDemo/GetImage',
                request_serializer=rpc__demo__pb2.ImageRequest.SerializeToString,
                response_deserializer=rpc__demo__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.GetTrailer = channel.unary_unary(
                '/RPCDemoPkg.RPCDemo/GetTrailer',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=rpc__demo__pb2.TrailerStatus.FromString,
                _registered_method=True)
        self.GetVelocity = channel.unary_unary(
                '/RPCDemoPkg.RPCDemo/GetVelocity',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=rpc__demo__pb2.Velocities.FromString,
                _registered_method=True)


class RPCDemoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMultCoords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrailer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVelocity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RPCDemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMultCoords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMultCoords,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=rpc__demo__pb2.MultCoords.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=rpc__demo__pb2.ImageRequest.FromString,
                    response_serializer=rpc__demo__pb2.ImageResponse.SerializeToString,
            ),
            'GetTrailer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrailer,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=rpc__demo__pb2.TrailerStatus.SerializeToString,
            ),
            'GetVelocity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVelocity,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=rpc__demo__pb2.Velocities.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RPCDemoPkg.RPCDemo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RPCDemoPkg.RPCDemo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RPCDemo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMultCoords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RPCDemoPkg.RPCDemo/GetMultCoords',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            rpc__demo__pb2.MultCoords.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RPCDemoPkg.RPCDemo/GetImage',
            rpc__demo__pb2.ImageRequest.SerializeToString,
            rpc__demo__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrailer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RPCDemoPkg.RPCDemo/GetTrailer',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            rpc__demo__pb2.TrailerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVelocity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RPCDemoPkg.RPCDemo/GetVelocity',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            rpc__demo__pb2.Velocities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
